x-app: &app
  build:
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    IS_DEBUG: "false"
  restart: unless-stopped

services:
  pg:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    <<: *app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    depends_on:
      pg:
        condition: service_healthy

  redis:
    image: redis:8-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 5s
      interval: 1m
      timeout: 3s
      retries: 5
    restart: unless-stopped

  taskiq-worker:
    <<: *app
    command: taskiq worker src.core.broker:broker src.crypto.tasks
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy

  taskiq-scheduler:
    <<: *app
    command: taskiq scheduler src.core.broker:scheduler src.crypto.tasks
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pgdata:
