"""Add tables for BTC and ETH

Revision ID: 035b6c563f7f
Revises:
Create Date: 2026-01-18 21:23:12.919229

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "035b6c563f7f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "btcs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_price", sa.String(), nullable=False),
        sa.Column("instrument_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "eths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_price", sa.String(), nullable=False),
        sa.Column("instrument_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eths")
    op.drop_table("btcs")
    # ### end Alembic commands ###
