"""collapse two models

Revision ID: b9c5874111fa
Revises: e760a433f1c2
Create Date: 2026-09-18 20:39:51.845504

"""

import typing

import sqlalchemy as sa

from alembic import op

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b9c5874111fa"
down_revision: str | Sequence[str] | None = "e760a433f1c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_currencies",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("index_price", sa.Float(), nullable=False),
        sa.Column("instrument_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crypto_currencies_ticker"),
        "crypto_currencies",
        ["ticker"],
        unique=False,
    )
    op.drop_table("btcs")
    op.drop_table("eths")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eths",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("index_price", sa.FLOAT(), nullable=False),
        sa.Column("instrument_name", sa.VARCHAR(), nullable=False),
        sa.Column("timestamp", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "btcs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("index_price", sa.FLOAT(), nullable=False),
        sa.Column("instrument_name", sa.VARCHAR(), nullable=False),
        sa.Column("timestamp", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_crypto_currencies_ticker"), table_name="crypto_currencies")
    op.drop_table("crypto_currencies")
    # ### end Alembic commands ###
